---
    - name: Block for System Update    
      when: ansible_os_family == "Ubuntu"
      block:
        - name: Update {{ update_resolv_conf.path }}
          lineinfile:
            path: "{{ update_resolv_conf.path }}"
            state: "{{ update_resolv_conf.state }}"
            owner: "{{ update_resolv_conf.owner }}"
            group: "{{ update_resolv_conf.group }}"
            line: "{{ item }}"
          loop: "{{ update_resolv_conf.data }}"