---
    - name: Create File System for Update
      file:
        path: "{{ update.file.path }}"
        owner: "{{ update.file.owner }}"
        group: "{{ update.file.group }}"
        mode: "{{ update.file.mode }}"
        state: "{{ update.file.state }}"
      when: "ansible_os_family == OS.type"
      register: create_filesystem
    - name: Copy & Execute Script
      script:
        chdir: "{{ copy.script.chdir }}"
        cmd: "{{ copy.script.cmd }}"
      when: "ansible_os_family == OS.type"
      register: execute_filesystem