---
    - name: Block for System Update
      when: "ansible_os_family == OS.type"
      block:
        - name: Create File System for Update
          file:
            path: "{{ update.file.path }}"
            owner: "{{ update.file.owner }}"
            group: "{{ update.file.group }}"
            mode: "{{ update.file.mode }}"
            state: "{{ update.file.state }}"
        - name: Copy & Execute Script
          script:
            chdir: "{{ copy.script.chdir }}"
            cmd: "{{ copy.script.cmd }}"
          notify: "Reboot now"