# Update DNS and Hostname
- name: Update DNS
  hosts: localhost_group
  vars_files:
    - "./vars/localhost_group.yml"
  tasks:
    - name: Update {{ update_resolv_conf.path }}
      lineinfile:
        path: "{{ update_resolv_conf.path }}"
        state: "{{ update_resolv_conf.state }}"
        owner: "{{ update_resolv_conf.owner }}"
        group: "{{ update_resolv_conf.group }}"
        line: "{{ item }}"
      loop: "{{ update_resolv_conf.data }}"